import os
import json
import math
import time
from collections import Counter
from pathlib import Path
from typing import Optional, Tuple, List

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset, Dataset
from sklearn.preprocessing import StandardScaler
import joblib
from tqdm import tqdm

# Centralized configuration
from config import CFG, DEVICE, ENN_PARAMS

from enn_models import EvidentialNetwork, evidential_loss

# ==============================================================================
# Helper Methods
# ==============================================================================

def _scaler_path() -> str:
    """Returns the dynamic path for the StandardScaler based on the active environment."""
    return os.path.join(os.path.dirname(CFG.MODEL_ENN_PATH), f"scaler_{CFG.ENV_NAME}_enn.pkl")

def _best_weights_path() -> str:
    """Returns the dynamic path for saving the best model checkpoint."""
    return os.path.join(os.path.dirname(CFG.MODEL_ENN_PATH), f"enn_best_{CFG.ENV_NAME}.pth")

def _meta_path() -> str:
    """Returns the dynamic path for saving model metadata (class mappings, etc.)."""
    return os.path.join(os.path.dirname(CFG.MODEL_ENN_PATH), f"enn_meta_{CFG.ENV_NAME}.json")

def get_uncertainty(model: EvidentialNetwork, obs_array: np.ndarray) -> float:
    """
    Calculates epistemic uncertainty for a given raw observation array.
    Automatically applies the pre-fitted standard scaler.
    """
    scaler = _load_scaler()
    input_dim = int(getattr(model, "input_dim", scaler.n_features_in_))
    obs_scaled = scaler.transform(obs_array.reshape(-1, input_dim))
    obs_tensor = torch.tensor(obs_scaled, dtype=torch.float32, device=DEVICE)

    model.eval()
    with torch.no_grad():
        out = model(obs_tensor)
        u = out["uncertainty"].squeeze(-1)

    return float(u.mean().item())

def load_trained_enn() -> EvidentialNetwork:
    """Safely initializes and loads the pre-trained Evidential Network weights."""
    meta = _load_enn_meta()
    num_classes = meta.get("num_classes", ENN_PARAMS["num_classes"])
    input_dim = meta.get("input_dim")
    if input_dim is None:
        try:
            input_dim = int(_load_scaler().n_features_in_)
        except (FileNotFoundError, AttributeError):
            input_dim = ENN_PARAMS["input_dim"]

    model = EvidentialNetwork(
        input_dim=int(input_dim),
        num_classes=num_classes,
        hidden_dim=ENN_PARAMS["hidden_dim"],
        dropout=CFG.ENN_DROPOUT,
    ).to(DEVICE)

    # Try loading best weights first, fallback to final epoch weights
    load_errors = []
    for path in [_best_weights_path(), CFG.MODEL_ENN_PATH]:
        if os.path.exists(path):
            try:
                model.load_state_dict(torch.load(path, map_location=DEVICE))
                break
            except (RuntimeError, KeyError, ValueError) as exc:
                load_errors.append(f"{path}: {exc}")
    else:
        detail = "; ".join(load_errors) or "no checkpoint files exist"
        raise RuntimeError(f"No compatible ENN checkpoint could be loaded: {detail}")

    model.eval()
    return model

# ==============================================================================
# Scaler & Meta Utilities
# ==============================================================================

def _load_scaler() -> StandardScaler:
    path = _scaler_path()
    if not os.path.exists(path):
        raise FileNotFoundError(f"Scaler not found at: {path}. Ensure the training pipeline ran successfully.")
    return joblib.load(path)

def _fit_and_save_scaler(obs: np.ndarray) -> StandardScaler:
    """Fits a scikit-learn StandardScaler to the training data and saves it to disk."""
    scaler = StandardScaler()
    scaler.fit(obs)
    path = _scaler_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    joblib.dump(scaler, path)
    return scaler

def _load_enn_meta() -> dict:
    path = _meta_path()
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {"num_classes": CFG.ENN_NUM_CLASSES}

# ==============================================================================
# Data and Mathematical Helpers
# ==============================================================================

def _load_tutor_split(path: Path) -> Tuple[np.ndarray, np.ndarray]:
    """Loads a specific npz split (train, val, or test) generated by the agent's tutor."""
    if not path.exists():
        raise FileNotFoundError(
            f"Required ENN tutor split not found: {path}. Expected train, val, "
            "and test .npz files under CFG.TUTOR_DIR."
        )

    with np.load(str(path)) as data:
        files = list(data.files)

        # Heuristics to find state (s_) and action (a_) keys, regardless of naming conventions
        s_key = next((k for k in files if k.startswith("s_") or k == "obs"), None)
        a_key = next((k for k in files if k.startswith("a_") or k == "act"), None)
        if s_key is None or a_key is None:
            raise ValueError(
                f"Invalid tutor split {path}: expected state/action arrays, found {files}"
            )

        obs = data[s_key].astype(np.float32)
        act = data[a_key].astype(np.int64).reshape(-1)
    if obs.ndim != 2 or act.ndim != 1 or len(obs) != len(act) or len(obs) == 0:
        raise ValueError(
            f"Invalid tutor split {path}: obs shape={obs.shape}, action shape={act.shape}; "
            "both must be non-empty with matching rows."
        )
    return obs, act

def _remap_topk(act_tr: np.ndarray, act_val: Optional[np.ndarray], act_te: Optional[np.ndarray], top_k: int) -> Tuple:
    """
    Filters the dataset to only include the top-K most frequent actions.
    Power grids have massive discrete action spaces, but most actions are never used.
    Limiting to top-K drastically reduces output dimensionality and improves ENN stability.
    """
    counts = Counter(act_tr.tolist())
    topk = [cls for cls, _ in counts.most_common(top_k)]
    mapping = {old: new for new, old in enumerate(topk)}

    def apply(arr):
        if arr is None: return None, None
        mask = np.array([a in mapping for a in arr])
        return (np.array([mapping[a] for a in arr[mask]], dtype=np.int64), mask)

    act_tr_r, mask_tr = apply(act_tr)
    act_val_r, mask_val = apply(act_val)
    act_te_r, mask_te = apply(act_te)

    return (act_tr_r, act_val_r, act_te_r, mask_tr, mask_val, mask_te, mapping, len(topk))

def compute_effective_weights(actions: np.ndarray, num_classes: int, beta: float = 0.999) -> torch.Tensor:
    """
    Computes Effective Number of Samples weights to handle extreme class imbalance.
    Prevents the model from being biased towards the "do nothing" action, ensuring
    rare topology-changing actions are penalized heavily if misclassified.
    Reference: https://arxiv.org/abs/1901.05555
    """
    counts = np.bincount(actions, minlength=num_classes)
    counts = np.maximum(counts, 1) # Avoid division by zero

    effective_num = 1.0 - np.power(beta, counts)
    weights = (1.0 - beta) / effective_num

    # Normalize weights so they sum to num_classes
    weights = weights / np.sum(weights) * num_classes

    return torch.tensor(weights, dtype=torch.float32, device=DEVICE)

class NoisyDataset(Dataset):
    """
    PyTorch Dataset wrapper that applies online Gaussian noise to observations.
    Acts as a data augmentation technique, improving the ENN's robustness to
    slight variations in grid states.
    """
    def __init__(self, obs, actions, noise_std):
        self.obs = torch.tensor(obs, dtype=torch.float32)
        self.actions = torch.tensor(actions, dtype=torch.long)
        self.noise_std = noise_std

    def __len__(self): return len(self.actions)

    def __getitem__(self, idx):
        x = self.obs[idx]
        if self.noise_std > 0:
            x = x + torch.randn_like(x) * self.noise_std
        return x, self.actions[idx]

def _cosine_with_warmup(optimizer, warmup, total):
    """
    Custom Learning Rate Scheduler:
    Linear warmup for early stability, followed by cosine annealing to smoothly
    converge to a minimum learning rate.
    """
    def lr_fn(ep):
        if ep < warmup: return ep / max(warmup, 1)
        p = (ep - warmup) / max(total - warmup, 1)
        return 0.5 * (1.0 + math.cos(math.pi * p))
    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_fn)

# ==============================================================================
# Main Training Loop
# ==============================================================================

def train_enn(top_k: int = CFG.ENN_TOP_K) -> EvidentialNetwork:
    """
    Executes the full Evidential Neural Network training pipeline.
    """
    print(f"[ENN] Loading Tutor Data from: {CFG.TUTOR_DIR}")

    # 1. Load and prepare datasets
    obs_tr, act_tr = _load_tutor_split(Path(CFG.TRAIN_FILE))
    obs_val, act_val = _load_tutor_split(Path(CFG.VAL_FILE))
    obs_te, act_te = _load_tutor_split(Path(CFG.TEST_FILE))

    input_dim = int(obs_tr.shape[1])
    for split_name, obs in (("validation", obs_val), ("test", obs_te)):
        if obs.shape[1] != input_dim:
            raise ValueError(
                f"ENN {split_name} feature width {obs.shape[1]} does not match "
                f"training width {input_dim}."
            )

    (act_tr, act_val, act_te, mask_tr, mask_val, mask_te, cls_mapping, n_cls) = _remap_topk(act_tr, act_val, act_te, top_k=top_k)

    obs_tr = obs_tr[mask_tr]
    obs_val = obs_val[mask_val]
    obs_te = obs_te[mask_te]
    if len(obs_val) == 0:
        print("[ENN] Validation split has no top-K actions; using test split for evaluation.")
        obs_val, act_val = None, None
    if len(obs_te) == 0:
        print("[ENN] Test split has no top-K actions; disabling test evaluation.")
        obs_te, act_te = None, None

    # 2. Compute handling strategies for imbalance and scale features
    class_weights = compute_effective_weights(act_tr, num_classes=n_cls, beta=0.999)
    print(f"[ENN] Calculated weights. Min: {class_weights.min():.3f} | Max: {class_weights.max():.3f}")

    scaler = _fit_and_save_scaler(obs_tr)
    obs_tr_s = scaler.transform(obs_tr)
    obs_val_s = scaler.transform(obs_val) if obs_val is not None else None
    obs_te_s = scaler.transform(obs_te) if obs_te is not None else None

    # 3. Initialize DataLoaders
    train_loader = DataLoader(
        NoisyDataset(obs_tr_s, act_tr, noise_std=CFG.ENN_NOISE_STD),
        batch_size=CFG.ENN_BATCH_SIZE,
        shuffle=True,
        num_workers=0
    )

    val_loader = None
    if obs_val_s is not None:
        val_loader = DataLoader(
            TensorDataset(torch.tensor(obs_val_s, dtype=torch.float32), torch.tensor(act_val, dtype=torch.long)),
            batch_size=CFG.ENN_BATCH_SIZE,
            shuffle=False
        )

    test_loader = None
    if obs_te_s is not None:
        test_loader = DataLoader(
            TensorDataset(torch.tensor(obs_te_s, dtype=torch.float32), torch.tensor(act_te, dtype=torch.long)),
            batch_size=CFG.ENN_BATCH_SIZE,
            shuffle=False
        )

    # 4. Initialize Model, Optimizer, and Scheduler
    model = EvidentialNetwork(
        input_dim=input_dim,
        num_classes=n_cls,
        hidden_dim=ENN_PARAMS["hidden_dim"],
        dropout=CFG.ENN_DROPOUT
    ).to(DEVICE)

    optimizer = torch.optim.AdamW(model.parameters(), lr=CFG.ENN_MAX_LR, weight_decay=CFG.ENN_WEIGHT_DECAY)
    scheduler = _cosine_with_warmup(optimizer, CFG.ENN_WARMUP, CFG.ENN_EPOCHS)

    best_val_loss = float("inf")
    patience_counter = 0
    best_path = _best_weights_path()
    if os.path.exists(best_path):
        os.remove(best_path)
        print(f"[ENN] Removed stale best-checkpoint candidate: {best_path}")

    print("\n" + "=" * 80)
    print("  ENN TRAINING — Tutor CurriculumAgent (EDL Loss)")
    print("=" * 80)

    t0 = time.time()

    # 5. Execute Training Loop
    progress = tqdm(range(1, CFG.ENN_EPOCHS + 1), desc="Training ENN", unit="epoch")
    for epoch in progress:
        model.train()
        tr_loss, tr_correct, tr_n = 0.0, 0, 0

        for obs_b, act_b in train_loader:
            obs_b, act_b = obs_b.to(DEVICE), act_b.to(DEVICE)

            out = model(obs_b)

            # Evidential loss computes NLL Type II + KL Divergence Penalty
            loss = evidential_loss(
                out["alpha"], act_b, epoch, CFG.ENN_EPOCHS,
                class_weights=class_weights,
                lam=CFG.ENN_EDL_LAMBDA
            )

            optimizer.zero_grad()
            loss.backward()

            # Gradient clipping prevents exploding gradients during the KL warmup phase
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            bs = obs_b.size(0)
            tr_loss += loss.item() * bs
            tr_correct += (out["prob"].argmax(-1) == act_b).sum().item()
            tr_n += bs

        scheduler.step()

        # 6. Evaluation Loop
        eval_loader = val_loader if val_loader is not None else test_loader
        val_info = {}

        if eval_loader is not None:
            model.eval()
            v_loss, v_correct, v_n = 0.0, 0, 0
            v_u = []

            with torch.no_grad():
                for obs_b, act_b in eval_loader:
                    obs_b, act_b = obs_b.to(DEVICE), act_b.to(DEVICE)
                    out = model(obs_b)

                    loss = evidential_loss(
                        out["alpha"], act_b, epoch, CFG.ENN_EPOCHS,
                        class_weights=class_weights,
                        lam=CFG.ENN_EDL_LAMBDA
                    )

                    bs = obs_b.size(0)
                    v_loss += loss.item() * bs
                    v_correct += (out["prob"].argmax(-1) == act_b).sum().item()
                    v_n += bs

                    # Track uncertainty to ensure it's behaving reasonably
                    v_u.append(out["uncertainty"].squeeze(-1).cpu())

            u_arr = torch.cat(v_u)
            val_info = {
                "val_loss": v_loss / v_n,
                "val_acc": v_correct / v_n,
                "u_mean": float(u_arr.mean()),
                "u_std": float(u_arr.std()),
            }

            # Standard Early Stopping implementation
            if val_info["val_loss"] < best_val_loss - 1e-5:
                best_val_loss = val_info["val_loss"]
                patience_counter = 0
                os.makedirs(os.path.dirname(best_path), exist_ok=True)
                torch.save(model.state_dict(), best_path)
            else:
                patience_counter += 1

        elapsed = time.time() - t0
        lr_now = optimizer.param_groups[0]["lr"]
        postfix = {
            "tr_loss": f"{tr_loss / tr_n:.4f}",
            "tr_acc": f"{tr_correct / tr_n:.3f}",
            "lr": f"{lr_now:.1e}",
            "elapsed": f"{elapsed:.0f}s",
        }
        if val_info:
            postfix.update({
                "val_loss": f"{val_info['val_loss']:.4f}",
                "val_acc": f"{val_info['val_acc']:.3f}",
                "U": f"{val_info['u_mean']:.3f}+/-{val_info['u_std']:.3f}",
            })
        progress.set_postfix(postfix)

        if patience_counter >= CFG.ENN_PATIENCE:
            tqdm.write(f"\n[ENN] Early stopping triggered at epoch {epoch}.")
            break

    # 8. Post-training: Load best weights and save artifacts
    if os.path.exists(best_path):
        model.load_state_dict(torch.load(best_path, map_location=DEVICE))

    os.makedirs(os.path.dirname(CFG.MODEL_ENN_PATH), exist_ok=True)
    torch.save(model.state_dict(), CFG.MODEL_ENN_PATH)

    with open(_meta_path(), "w") as f:
        json.dump({
            "input_dim": input_dim,
            "num_classes": n_cls,
            "class_mapping": {str(k): v for k, v in cls_mapping.items()},
            "top_k": n_cls,
            "environment": str(CFG.ENV_NAME),
        }, f, indent=2)

    return model

if __name__ == "__main__":
    model = train_enn(top_k=CFG.ENN_TOP_K)
    print("\n[ENN] Pipeline Completed.")
